version: "2"

services:
    db:
        image: centurylink/mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=177155
            - MYSQL_USERNAME=root
            - MYSQL_PASSWORD=177155
        ports: 
            - "3306:3306"
        volumes:
            - /var/data:/var/lib/mysql
    web:
        image: apache_php7
        restart: always
        ports:
            - "80:80"
        links:
            - db
        volumes:
            - /var/www/html:/var/www/html 
